# Generated by Django 5.2.1 on 2025-05-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auctions/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('admin', 'Admin'), ('user', 'Bidder')], default='user', max_length=10),
        ),
    ]
